#Docker Compose for testing
services:
  cocktails:
    container_name: cocktails
    build:
      context: .
      dockerfile: Dockerfile
    image: cocktails:local
    ports:
      - 3000:3000
    volumes:
      - ./resources/Markdown:/app/resources/Markdown
    environment:
      - EXT_API_KEY=Your_API_Key_Here
    restart: always